"""
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(n):
    if n < 0:
        print("Invalid input")
    elif n == 0:
        return 0
    elif n == 1 or n == 2:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

def sumEvenFibonacci(max_value):

    sum = 0

    fib_seq = [0, 1]

    if max_value < 0:
        print("Invalid input for fibonacci")

    i = 1
    while(fib_seq[i] < max_value):

        fib_seq.append(fib_seq[i] + fib_seq[i-1])

        if fib_seq[i] % 2 == 0:
            sum += fib_seq[i]

        i += 1

    return(sum)

print(sumEvenFibonacci(4000000))